### ISSUE TITLE
A error(bug) in the submit section

### ISSUE THREAD

**Issue by criticic** [opencodeiiita/opencode-leaderboard#2]
I created a submit points request for a issue in leaderboard,the pr link i provided was the pull request for completing two issues but when i tried to submit points for the second issue (which has the same pr link) the it showed this message and it kept loading forever:

**Except PR Link & Reference link field, all fields are mandatory**

possible cause: As both issues have same pull request , it is perhaps not accepting the second one..

Screenshot:
![abc](https://user-images.githubusercontent.com/40538506/52473626-3f752a80-2bbc-11e9-91f0-215e0ee2129c.PNG)

**Comment by criticic** [comment]
@Jigar3  @opencodebot please resolve this issue..i am not able to update my points..

**Comment by aswinzz** [comment]
@Jigar3

**Comment by Jigar3** [comment]
The PR link field is unique in the DB. That's why it isn't allowing you to create second request. Just put the PR link in the reference field we will take care

**Comment by criticic** [comment]
Thanks a lot👍👍☺☺
